name = "blazenote-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]
 
[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "<your-database-id>"
migrations_dir = "./migrations"

# TODO: In-Workshop Activities. Uncomment the code below:

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true